CREATE OR REPLACE FUNCTION GET_USR(
    P_ID VARCHAR2 DEFAULT NULL,
    P_USRNM VARCHAR2 DEFAULT NULL,
    P_EMAIL VARCHAR2 DEFAULT NULL,
    P_PASSWORD VARCHAR2 DEFAULT NULL
) RETURN USR_TAB PIPELINED AS
BEGIN
    FOR USR_REC IN(
        SELECT
            *
        FROM
            USR
        WHERE
            ID = P_ID
            OR (P_USRNM IS NULL
            AND USERNAME = P_USRNM)
            OR (P_EMAIL IS NULL
            AND EMAIL = P_EMAIL)
            OR (P_PASSWORD IS NULL
            AND PASSWORD = P_PASSWORD)
    ) LOOP
        PIPE ROW(USR_ROW(USR_REC.ID, USR_REC.USERNAME, USR_REC.EMAIL, USR_REC.PASSWORD));
    END LOOP;

    RETURN;
END GET_USR;
/
